export const Media =[
    {type:'image', url:require ('./1.jpg')},
    {type:'image', url:require ('./2.jpg')},
    {type:'image', url:require ('./3.jpg')},
    {type:'image', url:require ('./4.jpg')},
    {type:'image', url:require ('./5.jpg')},
    {type:'image', url:require ('./6.jpg')},
    {type:'image', url:require ('./7.jpg')},
    {type:'image', url:require ('./8.jpg')},
    {type:'image', url:require ('./9.jpg')},
    {type:'image', url:require ('./10.jpg')},
    {type:'image', url:require ('./11.jpg')},
    {type:'image', url:require ('./12.jpg')},
    {type:'image', url:require ('./13.jpg')},
    {type:'image', url:require ('./14.jpg')},
    {type:'image', url:require ('./15.jpg')},
    {type:'image', url:require ('./16.jpg')},
    {type:'image', url:require ('./17.jpg')},
    {type:'image', url:require ('./18.jpg')},
    {type:'image', url:require ('./19.jpg')},
    {type:'image', url:require ('./20.jpg')},
    {type:'image', url:require ('./21.jpg')},
    {type:'image', url:require ('./22.jpg')},
    {type:'image', url:require ('./23.jpg')},
    {type:'image', url:require ('./24.jpg')},
    {type:'image', url:require ('./25.jpg')},
    {type:'image', url:require ('./26.jpg')},
    {type:'image', url:require ('./27.jpg')},
    {type:'image', url:require ('./28.jpg')},
    {type:'image', url:require ('./29.jpg')},
    {type:'image', url:require ('./30.jpg')},
    {type:'image', url:require ('./31.jpg')},
    {type:'image', url:require ('./32.jpg')},
    {type:'image', url:require ('./33.jpg')},
    {type:'image', url:require ('./34.jpg')},
    {type:'image', url:require ('./35.jpg')},
    {type:'image', url:require ('./36.jpg')},
   


]